import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import logo from "../../public/flo_logo.png";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {" "}
        <header className="sticky top-0 z-50 bg-brand-green text-white flex items-center justify-between px-10 py-4">
          <div className="flex items-center">
            <Image
              src={logo}
              alt="Flo Energy Company Logo"
              width={60}
              height={60}
            />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
